### ISSUE TITLE
Feature: 수요일 외출 시 급식 수요 조사하기

### ISSUE THREAD

**Issue by dongchandev** [Team-B1ND/dodamdodam-server#111]
## 어떤 기능을 추가할 것인가요?
> 수요일에 외출 시 급식 수요를 조사하기 위한 alert창을 위한 api 개발 및 그를 위한 database 수정

## 기대 효과가 무엇인가요?
> 수요일 급식 수요 데이터를 수집할 수 있다.

**Comment by suw0n** [comment]
석식 시간 >= 외출 종료 시간으로 조건 잡고 카운트 쿼리 날리면 될 거 같아요

**Comment by dongchandev** [comment]
@suw0n 
복귀시간을 7:10으로 하고 나가는 사람이 많아서 그냥 클라이언트에서 alert창을 통해 수집하기로 결정했습니다.

**Comment by suw0n** [comment]
alert한 이후에 사용자가 선택하는 방식을 말하는 거죠? 사용자가 alert를 못보는 경우가 있을 수도 있는데... 아니면 외출 테이블에 급식 필드 추가한 뒤에 집계하는 것도 괜찮을 듯?
