### ISSUE TITLE
Feature: 졸업생 비활성화 api

### ISSUE THREAD

**Issue by dongchandev** [Team-B1ND/dodamdodam-server#116]
## 어떤 기능을 추가할 것인가요?
> Spring Batch를 활용하여 졸업생의 계정을 비활성화 한다.
-> batch가 불필요하다고 느낌
-> admin page에서 처리하기로 결정

## 기대 효과가 무엇인가요?
> 졸업생이 계정이 계속 활성화어 있으면 티쳐같은 경우 불편이 생기므로 비활성화하여 편의성을 개선한다.

**Comment by suw0n** [comment]
1년에 한 번 돌아가는 작업인데, spring batch app으로 만드는 건 투머치인거 같아요.

**Comment by suw0n** [comment]
디코봇으로 만들어보는건 어떤가요? 딸깍?

**Comment by dongchandev** [comment]
그럼 다시 한번 구현 방법을 생각해보겠습니다.
