### ISSUE TITLE
Refactor: exists query jpql

### ISSUE THREAD

**Issue by suw0n** [Team-B1ND/dodamdodam-server#14]
![image](https://github.com/Team-B1ND/dodamdodam-server/assets/99987376/534b8596-ccb4-4bfd-bc6e-5effd8f10dd6)

- 김희망 -

**Comment by esperar** [comment]
![image](https://github.com/Team-B1ND/dodamdodam-server/assets/105429536/28a11584-06d7-4df7-aaa4-94978dbc6ad3)

**Comment by esperar** [comment]
```java
var fetchOne = queryFactory.selectOne()
    .from(nightStudy)
    .where(nightStudy.getStudent().equals(student).and(...// condition))

return fetchOne != null;
```
